---
title: "Extension typologies and sustainable intensification: Evidence from West Africa"
subtitle: "Supplementary Material (Full model tables and robustness check)"
author: ''
date: "Last updated: `r Sys.time()`"
output: 
 bookdown::pdf_document2:
    keep_tex: true
    template: ../helper_utilities/my_templet.tex
    #highlight: zenburn
header-includes:
   - \usepackage[margin=2.8cm]{geometry}
   - \renewcommand{\contentsname}{Table of Contents}
   - \usepackage{enumitem}
   - \usepackage{pifont}
   - \renewcommand{\labelitemi}{$\rightarrow$}
   - \usepackage{tocloft}
   - \renewcommand\cftsecleader{\cftdotfill{\cftdotsep}}
   - \usepackage{hyperref}
   - \hypersetup{linkcolor = blue}
   - \usepackage{hanging}
   - \usepackage[T1]{fontenc}
   - \usepackage{graphicx}
   - \usepackage{booktabs,threeparttablex}
   - \usepackage{pdflscape}
   - \usepackage{fvextra}
   - \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
   - \usepackage{lmodern}
   - \usepackage{nimbusmono}
   - \renewcommand{\thetable}{SM\arabic{table}}
   - \setlength{\cfttabnumwidth}{1cm}

toc: false
toccolor: 'blue'
mainfont: 'lm'
toc-title: "Table of Contents"
---

```{r setup, include=FALSE, warning=FALSE, comment=FALSE}
knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE,
  echo = FALSE,
  tidy = TRUE,
  tidy.opts = list(width.cutoff = 60),
  out.width = "100%"
)

options(width = 100)
# load the required libraries



# load the required libraries
pacman::p_load(
jsonlite,
sjlabelled,
labelled,
dataMaid,
plotly,
wesanderson,
ggthemes,
hrbrthemes,
sjmisc,
expss,
haven,
knitr,
kableExtra,
ggstream,
ggstatsplot,
highcharter,
tidyverse
)
```
\newpage

\newpage
\listoftables
\newpage

```{r, echo=FALSE}
list_of_tables <- list()
file_names <- list.files(here::here("tables"), pattern = "*.txt")

for(i in 1:length(file_names)){
  list_of_tables[[i]] <- readr::read_delim(here::here("tables", file_names[[i]]), delim = "\t", escape_double = FALSE, trim_ws = TRUE, skip = 1,na = "empty" )
}


names(list_of_tables) <- str_replace(file_names, ".txt", "")


change_names <- function(df){
  names(df) <- str_replace(names(df), "_", "-")
  return(df)
}

list_of_tables <- purrr::map(list_of_tables, change_names)

clean_space <- function(df) {
  df %>%
    mutate_all(~ (str_replace_all(., "%", "\\\\%")))%>%
    mutate_all(~(str_replace_all(., "_", "\\\\_")))%>%
    mutate_all(~(str_replace_all(., "#", "\\\\#")))
}

list_of_tables <- purrr::map(list_of_tables, clean_space)


color_significance <- function(df){
  df[-1] <- lapply(
  df[-1], function(x){
    cell_spec(x, background = ifelse(str_count(x, "\\*")==1, "#8C2981", ifelse(str_count(x, "\\*")==2, "#641A80", ifelse(str_count(x, "\\*")==3, "#3C0F70", "white"))),color = ifelse(str_count(x, "\\*")>=1, "White", "black" ),bold = ifelse(str_count(x, "\\*")>=1,T, F ))
  }
)
  
  return(df)
}

bold_significance <- function(df){
  df[-1] <- lapply(
  df[-1], function(x){
    cell_spec(x, bold = ifelse(str_count(x, "\\*")>=1,T, F ))
  }
)
  
  return(df)
}
```

\newpage



```{r}

df <- list_of_tables$Result2%>%
  mutate(
    LABELS = case_when(
      LABELS=="" ~ VARIABLES,
      TRUE ~ LABELS
    )
  )%>%
  select(-VARIABLES)%>%
  rename(variables = LABELS)%>%
  bold_significance()


kableExtra::kbl(df, longtable = T, booktabs = T, escape=F, col.names = c("variables", "Intercropping","Intercropping","Crop rotation","Crop rotation", "Improved seeds", "Improved seeds", "Organic fertilisers", "Organic fertilisers"), align="lrrr", caption = "Extension access and SI practices")%>%
kableExtra::landscape()%>%
add_header_above(c(" ", "(1)" = 2, "(2)" = 2, "(3)" = 2, "(4)" = 2))  %>%
kable_styling(font_size = 7, latex_options = c("repeat_header"))%>%
  row_spec(32, hline_after = T)%>%
  row_spec(37, hline_after = T)
```

\newpage

```{r}

df <- list_of_tables$Result3%>%
  mutate(
    LABELS = case_when(
      LABELS=="" ~ VARIABLES,
      TRUE ~ LABELS
    )
  )%>%
  select(-VARIABLES)%>%
  rename(variables = LABELS)%>%
  bold_significance()


kableExtra::kbl(df, longtable = T, booktabs = T, escape=F, col.names = c("variables", "Intercropping","Intercropping","Crop rotation","Crop rotation", "Improved seeds", "Improved seeds", "Organic fertilisers", "Organic fertilisers"), align="lrrr", caption = "Extension system and SI practices")%>%
  add_header_above(c(" ", "(1)" = 2, "(2)" = 2, "(3)" = 2, "(4)" = 2))  %>%
  kableExtra::landscape()%>%
kable_styling(font_size = 6, latex_options = c("repeat_header"))%>%
  row_spec(34, hline_after = T)%>%
  row_spec(39, hline_after = T)
```


\newpage


```{r}

df <- list_of_tables$Result4%>%
  mutate(
    LABELS = case_when(
      LABELS=="" ~ VARIABLES,
      TRUE ~ LABELS
    )
  )%>%
  select(-VARIABLES)%>%
  rename(variables = LABELS)%>%
  bold_significance()



kableExtra::kbl(df, longtable = T, booktabs = T, escape=F, col.names = c("variables", "Intercropping","Intercropping","Crop rotation","Crop rotation", "Improved seeds", "Improved seeds", "Organic fertilisers", "Organic fertilisers"), align="lrrr", caption = "Joint public-private extension and SI practices")%>%
  add_header_above(c(" ", "(1)" = 2, "(2)" = 2, "(3)" = 2, "(4)" = 2))  %>%
  kableExtra::landscape()%>%
kable_styling(font_size = 7, latex_options = c("repeat_header"))%>%
  row_spec(32, hline_after = T)%>%
  row_spec(37, hline_after = T)
```
\newpage

```{r}

df <- list_of_tables$Result5%>%
  mutate(
    LABELS = case_when(
      LABELS=="" ~ VARIABLES,
      TRUE ~ LABELS
    )
  )%>%
  select(-VARIABLES)%>%
  rename(variables = LABELS)%>%
  bold_significance()

kableExtra::kbl(df, longtable = T, booktabs = T, escape=F, col.names = c("variables", "Intercropping","Intercropping","Crop rotation","Crop rotation", "Improved seeds", "Improved seeds", "Organic fertilisers", "Organic fertilisers"), align="lrrr", caption = "Training and SI practices")%>%
  add_header_above(c(" ", "(1)" = 2, "(2)" = 2, "(3)" = 2, "(4)" = 2))  %>%
kable_styling(font_size = 7, latex_options = c("repeat_header"))%>%
kableExtra::landscape()%>%
  row_spec(32, hline_after = T)%>%
  row_spec(37, hline_after = T)
```

\newpage

```{r}

df <- list_of_tables$Result6%>%
  mutate(
    LABELS = case_when(
      LABELS=="" ~ VARIABLES,
      TRUE ~ LABELS
    )
  )%>%
  select(-VARIABLES)%>%
  rename(variables = LABELS)%>%
  bold_significance()




kableExtra::kbl(df, longtable = T, booktabs = T, escape=F, col.names = c("variables", "Intercropping","Intercropping","Crop rotation","Crop rotation", "Improved seeds", "Improved seeds", "Organic fertilisers", "Organic fertilisers"), align="lrrr", caption = "Extension access and training and SI practices")%>%
  add_header_above(c(" ", "(1)" = 2, "(2)" = 2, "(3)" = 2, "(4)" = 2))  %>%
  kableExtra::landscape()%>%
kable_styling(font_size = 7, latex_options = c("repeat_header"))%>%
  row_spec(32, hline_after = T)%>%
  row_spec(37, hline_after = T)
```
\newpage

```{r}

df <- list_of_tables$Result_rc_1%>%
  mutate(
    LABELS = case_when(
      LABELS=="" ~ VARIABLES,
      TRUE ~ LABELS
    )
  )%>%
  select(-VARIABLES)%>%
  rename(variables = LABELS)%>%
  bold_significance()



kableExtra::kbl(df, longtable = T, booktabs = T, escape=F, col.names = c("variables", "Intercropping","Intercropping","Crop rotation","Crop rotation", "Improved seeds", "Improved seeds", "Organic fertilisers", "Organic fertilisers"), align="lrrr", caption = "Extension impacts on practices (Household FE Estimator)")%>%
  kableExtra::landscape()%>%
kable_styling(font_size = 7, latex_options = c("repeat_header"))%>%
  add_header_above(c(" ", "(1)" = 2, "(2)" = 2, "(3)" = 2, "(4)" = 2))  %>%
  row_spec(27, hline_after = T)%>%
  row_spec(34, hline_after = T)
```


\newpage


```{r}
df <- list_of_tables$Result_rc_2%>%
  mutate(
    LABELS = case_when(
      LABELS=="" ~ VARIABLES,
      TRUE ~ LABELS
    )
  )%>%
  select(-VARIABLES)%>%
  rename(variables = LABELS)%>%
  bold_significance()


kableExtra::kbl(df, longtable = T, booktabs = T, escape=F, col.names = c("variables", "Intercropping","Crop rotation", "Improved seeds",  "Organic fertilisers"), align="lrrr", caption = "Hausman Taylor estimation")%>%
  kableExtra::landscape()%>%
kable_styling(font_size = 7, latex_options = c("repeat_header"))%>%
  row_spec(32, hline_after = T)%>%
  row_spec(37, hline_after = T)
```

